Setup and mobile first
Zilola-Nazarova/portfolio-zilola pull request #1
Opened 2023-03-23 08:40 UTC by Zilola-Nazarova

It's the first branch of my zilola-portfolio repository. I'm trying to build 2 sections of the mobile website using template 1 (from Figma).

These are the changes I propose for the main repository:
1. Update README.md and MIT.md files (the Microverse template), and delete unnecessary logo icons and images.
2. Create files (linters.yml, .gitignore, .hntrc, .stylelintrc.json) to set up the linters.
3. Download from Figma all necessary images (icons) and upload them to the ./images folder.
4. Create index.html and styles.css files.
5. Make necessary changes to index.html and styles.css files so that the result looks exactly like the Figma template.
6. Use flexbox where needed and responsive values (rems) instead of pixels.
7. Add a couple of button interactions.

2023-03-23 08:59 UTC, Zilola-Nazarova commented on styles.css
> +}
This commit should be named "Add 3 lines of code to avoid 'no-empty-source' error in Stylelint".
I didn't notice that in the previous commit, the styles.css file didn't include these 3 lines.

2023-03-24 00:29 UTC, Zilola-Nazarova commented on index.html
> -        <button class="burger"><i class="fa fa-bars"></i></button>
I tried using the link to the icon library in the <head> and appending the icons to the buttons, but it didn't work well.

This is the lesson I tried to use:
https://www.w3schools.com/howto/howto_css_icon_buttons.asp

Then I decided to use the icon from Figma templates. I put it as a background-image in CSS.

2023-03-24 14:46 UTC, TadesseDev requested changes
### Hi @Zilola-Nazarova 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7](https://user-images.githubusercontent.com/69077061/212385281-4797c58a-d358-423a-aa7c-832c22203865.gif)



## Highlights
 - [ ] Good job overall following the template design ✅
 - [ ]  Correct GitHub Flow  ✅
 - [ ]  Good commit history  ✅
 - [ ]  Good PR title/description  ✅
 - [ ]  All linters passed  ✅
 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 14:46 UTC, TadesseDev commented on index.html
> +        <button class="burger"></button>
- [x] Good job adding the log @Zilola-Nazarova, But we need to make sure our logo is a link. Please wrap `My Logo` in an `a` tag. This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

2023-03-24 14:46 UTC, TadesseDev commented on index.html
> +    </header>
- [x] Your design is almost exceptional @Zilola-Nazarova, But I notice your header seems to have more margin from the top compared to the figma design. Would you consider reducing the margin/padding from the top please. 
### Figma design 
![image](https://user-images.githubusercontent.com/69077061/227554142-3f2bcb42-20cc-4864-814f-d4bcccbc9c11.png)

### Your design 
![image](https://user-images.githubusercontent.com/69077061/227554320-d094ee98-25d9-4108-9ce3-3d9c0099d479.png)

2023-03-24 14:46 UTC, TadesseDev commented on index.html
> +      <p class="headline-item" id="about-me">I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and ha
- [x] Dear @Zilola-Nazarova, Please consider using a `section` tag for your `Headline` section. It represents a generic standalone section of the document, [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info.
- [x] I notice you have used `h1` tag for your logo and `h2` for your heading text. Its great you have one `h1` tag but please consider making your logo anchor `a` and `heading` text an `h1`. If you want that google (and other search engines) knows about a specific topic, in this case, you, use an `h1` tag. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info.

2023-03-24 14:46 UTC, TadesseDev commented on index.html
> +        </div>
- [ ] Dear @Zilola-Nazarova, The list of icons better use a `ul` tag to group them, and `li` for each icon, then wrap each icon with a link (`a` tag).

```html
<ul class="headline-item" id="icons">
          <li><a><img src="./images/twitter.svg" href="https://twitter.com/ZilolaNazarova6" /></a></li>
                    <li><a><img src="./images/Linkedin icon.svg" href="https://www.linkedin.com/in/zilola-nazarova-a64858265/" /></a></li>
                    <li><a><img src="./images/medium.svg" href="#" /></a></li>
                    <li><a><img src="./images/github.svg" href="https://github.com/Zilola-Nazarova" /></a></li>
                   <li><a> <img src="./images/Vector.svg" href="#" />          </a></li>
        </ul>   

```

2023-03-24 14:46 UTC, TadesseDev commented on index.html
> +        <div class="headline-item" id="icons">
- [x] Dear @Zilola-Nazarova, Please notice the `LET'S CONNECT` text is a link that is going to link to your contact information latter on. Please wrap it inside an anchor/button tag.

2023-03-24 14:46 UTC, TadesseDev commented on MIT.md
> -###### Please delete this line and the next one
- [x] Good job adding the MIT file, The problem is you need to update its content in regard to your name and project title. Please replace the [YEAR] with the current year.

2023-03-24 17:16 UTC, Zuhaib042 approved these changes
Hi @Zilola-Nazarova , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://media.giphy.com/media/QJsP0cTAJhg7O47ub2/giphy.gif)
## Highlights
✅ Good job implementing the requirements

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 17:16 UTC, Zuhaib042 commented on index.html
> +        <h1 class="headline-item" id="greeting">I’m Alexandra.<br /> Glad to see you!</h1>
- [OPTIONAL] Kindly consider personalizing by replacing `Alexandra` with your name. because it is your portfolio and you need to personalize it.

2023-03-24 17:37 UTC, merged